/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.chl.proton;

import org.testng.annotations.Test;
import static org.junit.Assert.*;

public class ProtontextTest {
    @Test public void test() {
        // Protontext classUnderTest = new Protontext();
        // assertTrue("someLibraryMethod should return 'true'", classUnderTest != null);
    }
}
